# Generated by Django 2.2 on 2019-04-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emailId', models.EmailField(max_length=50)),
                ('contact_no', models.CharField(max_length=12)),
                ('dat', models.DateTimeField()),
            ],
        ),
    ]
