# Generated by Django 2.2 on 2019-04-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20190426_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student1',
            name='contact_no',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='student1',
            name='emailId',
            field=models.EmailField(max_length=254),
        ),
    ]
