# Generated by Django 2.2 on 2019-04-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20190426_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student1',
            name='emailId',
            field=models.EmailField(max_length=100),
        ),
    ]
