# Generated by Django 2.2 on 2019-04-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20190426_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student1',
            old_name='emailId',
            new_name='email_id',
        ),
    ]
