# Generated by Django 2.2 on 2019-04-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20190429_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student1',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
